package ru.staffly.schedule.model;

public enum ScheduleAuditAction {
    CREATED,
    UPDATED,
    DELETED,
    OWNER_CHANGED,
    PREFERENCE_COLLECTION_STARTED,
    PREFERENCE_COLLECTION_CLOSED,
    PREFERENCE_PARTICIPANT_ADDED,
    PREFERENCE_PARTICIPANT_REMOVED,
    PREFERENCE_COLLECTION_REOPENED,
    PREFERENCE_COLLECTION_INVALIDATED,
    APPLIED_PREFERENCE_DRAFT_INVALIDATED,
    PREFERENCES_APPLIED,
    AUTO_BUILD_APPLIED,
    PUBLISHED,
    SHIFT_REQUEST_CREATED,
    SHIFT_REQUEST_APPROVED,
    SHIFT_REQUEST_REJECTED,
    SHIFT_REQUEST_AUTO_REJECTED
}
