package ru.staffly.schedule.model;

public enum ScheduleAuditAction {
    CREATED,
    UPDATED,
    DELETED,
    OWNER_CHANGED,
    PREFERENCE_COLLECTION_STARTED,
    PREFERENCE_COLLECTION_CLOSED,
    PUBLISHED,
    SHIFT_REQUEST_CREATED,
    SHIFT_REQUEST_APPROVED,
    SHIFT_REQUEST_REJECTED,
    SHIFT_REQUEST_AUTO_REJECTED
}
