package ru.staffly.inbox.service;

import ru.staffly.inbox.model.BusinessNotificationKind;
import ru.staffly.member.model.RestaurantMember;
import ru.staffly.restaurant.model.Restaurant;
import ru.staffly.user.model.User;

import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;

/**
 * One recipient/resource-kind group produced by a single backend business command.
 * The operation id is generated by the orchestrator once and shared by all of its groups.
 */
public record BusinessNotificationCommand(
        Restaurant restaurant,
        UUID operationId,
        RestaurantMember recipient,
        User actor,
        BusinessNotificationKind kind,
        String inboxText,
        String pushText,
        LocalDate expiresAt
) {
    public BusinessNotificationCommand {
        Objects.requireNonNull(restaurant, "restaurant is required");
        Objects.requireNonNull(restaurant.getId(), "restaurant.id is required");
        Objects.requireNonNull(operationId, "operationId is required");
        Objects.requireNonNull(kind, "kind is required");

        inboxText = normalize(inboxText);
        pushText = normalize(pushText);
        if (inboxText == null && pushText == null) {
            throw new IllegalArgumentException("inboxText or pushText is required");
        }
        if (inboxText == null) {
            inboxText = pushText;
        }
    }

    public Long restaurantId() {
        return restaurant.getId();
    }

    private static String normalize(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return value.trim();
    }
}
