spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}
  creator:
    phones: ${CREATOR_PHONES}
  public-base-url: ${PUBLIC_BASE_URL:https://staffly.store}
  push:
    vapid:
      public-key: ${VAPID_PUBLIC_KEY}
      private-key: ${VAPID_PRIVATE_KEY}
      subject: ${VAPID_SUBJECT}
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    public-bucket: ${S3_PUBLIC_BUCKET:staffly-prod}
    private-bucket: ${S3_PRIVATE_BUCKET:staffly-private}

logging:
  level:
    ru.staffly: INFO
